app/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

# 表单的类
class Dhfs(db.Model):
    """
    电话费表
    """
    __tablename__ = 'dhfs'
    sd = db.Column(db.Integer, primary_key=True)
    tr = db.Column(db.Float())
    dx = db.Column(db.Float())
    kt = db.Column(db.Float())
    yx = db.Column(db.Float())
    hj = db.Column(db.Float())

    def get_columns(self):
        return tuple(col.name for col in self.__table__.columns)

    def to_dict(self):
        return dict([(col, getattr(self, col)) for col in self.get_columns()])

    def __repr__(self):
        return '{0}'.format(self.hj)



class Dyfs(db.Model):
    """
    打印费表
    """
    __tablename__ = 'dyfs'
    sd = db.Column(db.Integer, primary_key=True)
    fy = db.Column(db.Float())
    bz = db.Column(db.String(20))

    def get_columns(self):
        return [col.name for col in self.__table__.columns]

    def to_dict(self):
        return dict([(col, getattr(self, col)) for col in self.get_columns()])
 




class Kdfs(db.Model):
    """
    电信联通表
    """
    __tablename__ = 'kdfs'
    sd = db.Column(db.String(10), primary_key=True)
    fy = db.Column(db.Float())
    bz= db.Column(db.String(15))

    def __repr__(self):
        return '{0}'.format(self.fy)

app/forms.py
from wtforms import Form,FloatField,SubmitField,StringField,IntegerField
from wtforms.validators import DataRequired, Length

class NEDhfForm(Form):
    sd = IntegerField('费用账期:', validators=[DataRequired(), Length(4,6)])
    tr = FloatField('天润费用:', validators=[DataRequired(), Length(6,7)])
    dx = FloatField('东信费用:', validators=[DataRequired(), Length(6,7)])
    kt = FloatField('科天费用:', validators=[DataRequired(), Length(6,7)])
    yx = FloatField('颐信费用:', validators=[DataRequired(), Length(6,7)])
    hj = FloatField('总计费用:', validators=[DataRequired(), Length(6,7)])
    submit = SubmitField('提交:', validators=[DataRequired(), Length(8,10)])

class DyfForm(Form):
    sd = IntegerField('费用账期:', validators=[DataRequired(), Length(4,6)])
    fy = FloatField('打印费用:', validators=[DataRequired(), Length(4,6)])
    bz = StringField('备注信息:', validators=[DataRequired(), Length(1,20)])
    submit = SubmitField('提交:', validators=[DataRequired(), Length(4,6)])


class KdfForm(Form):
    sd = StringField('费用账期:', validators=[DataRequired(), Length(4,6)])
    fy = FloatField('费用明细:', validators=[DataRequired(), Length(8,10)]) 
    bz = StringField('备注信息:', validators=[DataRequired(), Length(1,20)])
    submit = SubmitField('提交:')   

app/__init__.py
from flask import Flask
import configs
from app.models import db
from app.views import fydsbp
from flask_bootstrap import Bootstrap

def create_app():
    app = Flask(__name__)

    # 配置
    app.config.from_object(configs)

    # 初始化db
    db.app = app
    db.init_app(app)

    # 注册蓝图
    app.register_blueprint(fydsbp)


    bootstrap = Bootstrap(app)
    return app

app/controllers.py
from app.models import db


# 电话费表的控制类
class DhfsDao():
    # 新增记录
    def create_rd(self, new_rd):
        db.session.add(new_rd)
        db.session.commit()
        return new_rd

    # def create_rd(self,rd_sd,rd_tr,rd_dx,rd_kt,rd_yx,rd_hj):
        # new_rd = Dhfs(sd=rd_sd,tr=rd_tr,dx=rd_dx,kt=rd_kt,yx=rd_yx,hj=rd_hj)
        # db.session.add(new_rd)
        # db.session.commit()
        # return new_rd

    # 删除记录
    def delete_rd(self, mds, rd):
        to_delete_rd = mds.query.get(rd.sd)
        db.session.delete(to_delete_rd)
        db.session.commit()
        return True
    # 编辑记录
    def update_rd(self,mds, rd):
        modified_rd = mds.query.get(rd.sd)
        db.session.commit()
        return modified_rd

    # 显示表
    def list_all(self, mds):
        return mds.query.order_by().all()

    # 查询记录
    def get_rd(self, mds, sd):
        return mds.query.get(sd)

app/views.py
from flask import Blueprint, render_template, request, redirect, url_for,flash
from app.forms import NEDhfForm, DyfForm, KdfForm
from app.controllers import DhfsDao
from app.models import Dhfs, Dyfs,Kdfs


# 定义蓝图
fydsbp = Blueprint('fydsbp', __name__, template_folder='templates')



# 电话费表单路由
@fydsbp.route('/', methods=['GET', 'POST'])
def index():
    form = NEDhfForm()
    rdservice = DhfsDao()
    rds = rdservice.list_all(Dhfs)
    tls= "提交记录"
    if request.method == 'POST':
        new_rd = Dhfs(
            sd = request.form['sd'],
            tr = request.form['tr'],
            dx = request.form['dx'],
            kt = request.form['kt'],
            yx = request.form['yx'],
            hj = request.form['yx']
        )
        DhfsDao().create_rd(new_rd)
        return redirect(url_for('fydsbp.index'))
    return render_template('index.html', rds=rds, form=form, tls=tls)


@fydsbp.route('/edit/<int:rd_sd>', methods=['GET','POST'])
def edit_rd(rd_sd):
    form = NEDhfForm()
    rd = DhfsDao().get_rd(Dhfs, rd_sd)
    rds = DhfsDao().list_all(Dhfs)
    tls = '修改记录'
    if request.method == 'POST':
        rd.tr = request.form['tr']
        rd.dx = request.form['dx']
        rd.kt= request.form['kt']
        rd.yx= request.form['yx']
        rd.hj= request.form['hj']
        DhfsDao().update_rd(Dhfs, rd)
        return redirect(url_for('fydsbp.index'))        
    form.sd.data = rd.sd
    form.tr.data = rd.tr
    form.dx.data = rd.dx
    form.kt.data = rd.kt
    form.yx.data = rd.yx
    form.hj.data = rd.hj
    return render_template('index.html', rds=rds, form=form, tls = tls)


@fydsbp.route('/delete/<int:rd_sd>', methods=['GET'])
def delete_rd(rd_sd):
    rdsdao = DhfsDao()
    rd = rdsdao.get_rd(Dhfs,rd_sd)
    rdsdao.delete_rd(Dhfs, rd)
    flash('Success deletc')
    return redirect(url_for('fydsbp.index'))




# 打印费用表单

@fydsbp.route('/dy', methods=['GET', 'POST'])
def dyfs():
    form = DyfForm()
    rds =DhfsDao().list_all(Dyfs)
    if request.method == 'POST':
        new_rd = Dyfs(
            sd = request.form['sd'],
            fy = request.form['fy'],
            bz = request.form['bz']
        )
        DhfsDao().create_rd(new_rd)
        return redirect(url_for('fydsbp.dyfs'))
    return render_template('dyfs.html', rds=rds, form=form, tls="提交记录")

@fydsbp.route('/del/<int:rd_sd>', methods=['GET'])
def del_rd(rd_sd):
    rdsdao = DhfsDao()
    rd = rdsdao.get_rd(Dyfs,rd_sd)
    rdsdao.delete_rd(Dyfs, rd)
    flash('Success deletc')
    return redirect(url_for('fydsbp.dyfs'))


@fydsbp.route('/editfyd/<int:rd_sd>', methods=['GET','POST'])
def ed_rd(rd_sd):
    form = DyfForm()
    rd = DhfsDao().get_rd(Dyfs, rd_sd)
    rds = DhfsDao().list_all(Dyfs)
    print(rds)
    if request.method == 'POST':
        rd.sd = request.form['sd']
        rd.fy = request.form['fy']
        rd.bz= request.form['bz']
        DhfsDao().update_rd(Dyfs, rd)
        return redirect(url_for('fydsbp.dyfs'))        
    form.sd.data = rd.sd
    form.fy.data = rd.fy
    form.bz.data = rd.bz
    return render_template('dyfs.html',rds=rds,form=form, tls="修改记录")


# 宽带费用表单

@fydsbp.route('/kd', methods=['GET', 'POST'])
def kdfs():
    form = KdfForm()
    rds =DhfsDao().list_all(Kdfs)
    if request.method == 'POST':
        new_rd = Kdfs(
            sd = request.form['sd'],
            fy = request.form['fy'],
            bz = request.form['bz']
        )
        DhfsDao().create_rd(new_rd)
        return redirect(url_for('fydsbp.kdfs'))
    return render_template('kdfs.html', rds=rds, form=form, tls="提交记录")

@fydsbp.route('/del_fyds/<string:rd_sd>', methods=['GET'])
def del_kdrd(rd_sd):
    rdsdao = DhfsDao()
    rd = rdsdao.get_rd(Kdfs,rd_sd)
    rdsdao.delete_rd(Kdfs, rd)
    flash('Success deletc')
    return redirect(url_for('fydsbp.kdfs'))


@fydsbp.route('/editkds/<string:rd_sd>', methods=['GET','POST'])
def ed_kdrd(rd_sd):
    form = KdfForm()
    rd = DhfsDao().get_rd(Kdfs, rd_sd)
    rds = DhfsDao().list_all(Kdfs)
    print(rds)
    if request.method == 'POST':
        rd.sd = request.form['sd']
        rd.fy = request.form['fy']
        rd.bz= request.form['bz']
        DhfsDao().update_rd(Kdfs, rd)
        return redirect(url_for('fydsbp.kdfs'))        
    form.sd.data = rd.sd
    form.fy.data = rd.fy
    form.bz.data = rd.bz
    return render_template('kdfs.html',rds=rds,form=form, tls="修改记录")

app/templates/base.html
{% extends "bootstrap/base.html"  %}
{% block title %}Flask{% endblock %}
{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">PMSsystem</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">电话费</a></li>
                <li><a href="/dy">打印费</a></li>
                <li><a href="/kd">宽带费</a></li>                 
            </ul>
        </div>
    </div>
</div>

{% endblock %}

{% for message in get_flashed_messages() %}
<div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}

{% block content %}
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/dyfs.html
{% extends "base.html" %}

{% block title %}首页{% endblock %}

{% block page_content %}
<h4> {{ rds|length }} Notes: </h4>
    <table class="table table-bordered">
    <tr>
        <th>费用账期</th>
        <th>费用金额</th>
        <th>备注信息</th>
    </tr>
        {% for rd in rds %}
            <tr>
                <td> {{rd.sd}} </td>
                <td> {{rd.fy}} </td>
                <td> {{rd.bz}} </td> 
            </tr>
        {% endfor %}
    </table>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}首页{% endblock %}

{% block page_content %}
<h4> {{ rds|length }} Notes: </h4>
    <table class="table table-bordered">
    <tr>
        <th>费用账期</th>
        <th>天润</th>
        <th>东信</th>
        <th>科天</th>
        <th>颐信</th>
        <th>总计</th>
        <th>操作</th>
    </tr>
        {% for rd in rds %}
            <tr>
                <td> {{rd.sd}} </td>
                <td> {{rd.tr}} </td>
                <td> {{rd.dx}} </td> 
                <td> {{rd.kt}} </td>
                <td> {{rd.yx}} </td>
                <td> {{rd.hj}} </td> 
                <td>
                    <a href="{{ url_for('fydsbp.edit_rd',rd_sd=rd.sd) }}">编辑</a>
		            <a href="{{ url_for('fydsbp.delete_rd',rd_sd=rd.sd) }}">删除</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <br>
    <br>
    <br>
    <br>
<h4>{{ tls }}</h4>
<form method="POST">
    {{ form.sd.label }}{{ form.sd }}<br/>
    {{ form.tr.label }}{{ form.tr }}<br/>
    {{ form.dx.label }}{{ form.dx }}<br/>
    {{ form.kt.label }}{{ form.kt }}<br/>
    {{ form.yx.label }}{{ form.yx }}<br/>
    {{ form.hj.label }}{{ form.hj }}<br/>
    {{ form.submit}}
</form>

{% endblock %}

app/templates/kdfs.html
{% extends "base.html" %}

{% block title %}首页{% endblock %}

{% block page_content %}
<h4> {{ rds|length }} Notes: </h4>
    <table class="table table-bordered">
    <tr>
        <th>费用账期</th>
        <th>费用金额</th>
        <th>备注信息</th>
        <th>操作</th>
    </tr>
        {% for rd in rds %}
            <tr>
                <td> {{ rd.sd }} </td>
                <td> {{ rd.fy }} </td>
                <td> {{ rd.bz }} </td>
                <td> 
                    <a href="{{ url_for('fydsbp.ed_kdrd',rd_sd=rd.sd) }}">编辑</a>
                    <a href="{{ url_for('fydsbp.del_kdrd',rd_sd=rd.sd) }}">删除</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <br>
    <br>  
    <br>
    <br>
<h4>{{ tls }}</h4>
    <form method="POST">
        <td> {{ form.sd.label }}{{ form.sd }} </td><br/>
        <td> {{ form.fy.label }}{{ form.fy }} </td><br/>
        <td> {{ form.bz.label }}{{ form.bz }} </td><br/>
        <td> {{ form.submit}} </td>
    </form>
{% endblock %}